baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'El Blog de Gonzalo'
theme = "hugo-theme-stack"
disqusShortname = "el-blog-de-gonzalo"

[menu]
    [[menu.main]]
        identifier = "home"
        name = "Home"
        url = "/"
        weight = -100
        pre = "home"
    [[menu.main]]
        identifier = "sobre-mi"
        name = "LinkedIn"
        url = "https://www.linkedin.com/in/gonzalo-garc%C3%ADa-vega-168a59263/"
        weight = -90
        pre = "user"
    [[menu.main]]
        identifier = "archives"
        name = "Github"
        url = "https://github.com/GonzaloGG10?tab=repositories"
        weight = -70
        pre = "archives"
