name: Deploy Images to GHCR

env:
  DOTNET_VERSION: '6.0.x'

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  push-store-image:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: './'
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

            build_and_push:
                name: Build image & push
                runs-on: ubuntu-latest
                permissions:
                  contents: read
                  packages: write

      - name: 'Build Inventory Image'
        run: |
          docker build . --tag ghcr.io/gonzalogg10/prueba2:latest
          docker push ghcr.io/gonzalogg10/prueba2:latest

